name: ESMBenchmarkViz_dev

dependencies:
  - python>=3.7
  - numpy
  - bokeh
  - matplotlib
  # test
  - pre_commit
  - pytest
  # documentation
  - sphinx
  - sphinx-autosummary-accessors
  - nbsphinx
  - furo
